# Generated by Django 5.2 on 2026-03-03 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birthdays', '0004_birthdayprofile_gender_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('CARD', 'Card'), ('FLOWER', 'Flower'), ('MESSAGE', 'Message'), ('BADGE', 'Badge'), ('VIDEO', 'Video')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='gbp', max_length=10)),
                ('platform_fee_bps', models.PositiveIntegerField(default=3000)),
                ('preview_asset_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'price'],
            },
        ),
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('custom_message', models.TextField(blank=True)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=15)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('celebrant_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birthday_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_purchases', to='birthdays.birthdayprofile')),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_purchases', to=settings.AUTH_USER_MODEL)),
                ('celebrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='gifts.giftproduct')),
            ],
        ),
    ]
