# Generated by Django 5.2 on 2026-03-09 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0009_ai_gift_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftproduct',
            name='customization_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic field schema used to build the gift customization form.'),
        ),
        migrations.AlterField(
            model_name='giftproduct',
            name='renderer_type',
            field=models.CharField(blank=True, choices=[('CARD_TEMPLATE', 'Card template'), ('FLOWER_GIFT', 'Flower gift'), ('ANIMATED_MESSAGE', 'Animated message'), ('BADGE_GIFT', 'Badge gift'), ('VIDEO_TEMPLATE', 'Video template')], max_length=32),
        ),
        migrations.AlterField(
            model_name='giftproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gifttemplate',
            name='renderer_type',
            field=models.CharField(choices=[('CARD_TEMPLATE', 'Card template'), ('FLOWER_GIFT', 'Flower gift'), ('ANIMATED_MESSAGE', 'Animated message'), ('BADGE_GIFT', 'Badge gift'), ('VIDEO_TEMPLATE', 'Video template')], max_length=32),
        ),
    ]
