# Generated by Django 5.2 on 2026-03-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPLICATION_RECEIVED', 'Application received'), ('APPLICATION_APPROVED', 'Application approved'), ('APPLICATION_DECLINED', 'Application declined'), ('EVENT_REMINDER', 'Event reminder'), ('BIRTHDAY_REMINDER', 'Birthday reminder'), ('MODERATION_PENDING', 'Moderation pending')], max_length=40),
        ),
    ]
