# Generated by Django 5.2 on 2026-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuepartner',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venuepartner',
            name='neighborhood_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='venuepartner',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
