# Generated by Django 5.2 on 2026-02-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='birthdayevent',
            new_name='events_birt_state_cfb187_idx',
            old_name='events_birt_state_3d9546_idx',
        ),
    ]
