# Generated by Django 5.2 on 2026-03-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_birthdayevent_target_amount_and_expense_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(default='🎂', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('defaults', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='birthdayevent',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.curatedpack'),
        ),
    ]
