# Generated by Django 5.2 on 2026-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcontribution',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportcontribution',
            name='supporter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supportcontribution',
            name='supporter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='birthdayprofile',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('LINK_ONLY', 'Link only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=16),
        ),
        migrations.AlterField(
            model_name='supportcontribution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
    ]
